export const ProductSpecificationsMap = {
  "Mobile Phone": [
    "model",
    "operatingSystem",
    "processor",
    "ram",
    "storage",
    "batteryCapacity",
    "screenSize",
    "camera",
    "simType",
    "connectivity",
    "chipset",
    "connectionType",
    "colors",
  ],
  Laptop: [
    "model",
    "processor",
    "ram",
    "storage",
    "graphicsCard",
    "size",
    "operatingSystem",
    "screenSize",
    "connectivity",
    "chipset",
    "connectionType",
    "colors",
    "gpuModel",
  ],
  TV: [
    "model",
    "screenSize",
    "resolution",
    "displayType",
    "smartTv",
    "operatingSystem",
    "connectivity",
    "refreshRate",
    "chipset",
    "connectionType",
    "colors",
  ],
  Tablet: [
    "model",
    "operatingSystem",
    "processor",
    "ram",
    "storage",
    "size",
    "camera",
    "batteryCapacity",
    "connectivity",
    "screenSize",
    "stylusSupport",
    "chipset",
    "connectionType",
    "colors",
  ],
  MacBook: [
    "model",
    "chip",
    "ram",
    "storage",
    "size",
    "batteryLife",
    "operatingSystem",
    "screenSize",
    "ports",
    "chipset",
    "connectionType",
    "colors",
  ],
  Projector: [
    "model",
    "Resolution",
    "Brightness",
    "Projection Technology",
    "Connectivity",
    "Aspect Ratio",
    "Throw Distance",
    "Built In Speakers",
    "Chipset",
    "Connection Type",
    "Colors",
  ],
  Camera: [
    "model",
    "cameraType",
    "sensorSize",
    "megapixels",
    "lensMountType",
    "videoResolution",
    "iosRange",
    "batteryLife",
    "connectivity",
    "screenType",
    "chipset",
    "connectionType",
    "colors",
  ],
};

export const ColorOptions = [
  "Red",
  "Blue",
  "Green",
  "Black",
  "White",
  "Yellow",
  "Pink",
  "Purple",
  "Gray",
  "Orange",
  "Brown",
  "Cyan",
  "Magenta",
  "Gold",
  "Silver",
  "Beige",
  "Teal",
  "Navy",
  "Maroon",
  "Olive",
  "Lime",
  "Indigo",
  "Violet",
  "Turquoise",
  "Lavender",
  "Coral",
  "Chocolate",
  "Ivory",
  "Amber",
  "Mint",
  "Rose",
  "Salmon",
  "Mustard",
  "Peach",
  "Plum",
  "Azure",
  "Burgundy",
  "Crimson",
  "Emerald",
  "Khaki",
];
