export const ProductSpecificationsMap = {
  "Mobile Phone": [
    "Model",
    "Operating System",
    "Processor",
    "RAM",
    "Storage",
    "Battery Capacity",
    "Screen Size",
    "Camera",
    "SIM Type",
    "Connectivity",
    "Chipset",
    "Connection Type",
    "Colors",
  ],
  Laptop: [
    "Model",
    "Processor",
    "RAM",
    "Storage",
    "Graphics Card",
    "Size",
    "Operating System",
    "Screen Size",
    "Connectivity",
    "Chipset",
    "Connection Type",
    "Colors",
    "GPU Model",
  ],
  TV: [
    "Model",
    "Screen Size",
    "Resolution",
    "Display Type",
    "Smart TV",
    "Operating System",
    "Connectivity",
    "Refresh Rate",
    "Chipset",
    "Connection Type",
    "Colors",
  ],
  Tablet: [
    "Model",
    "Operating System",
    "Processor",
    "RAM",
    "Storage",
    "Size",
    "Camera",
    "Battery Capacity",
    "Connectivity",
    "Screen Size",
    "Stylus Support",
    "Chipset",
    "Connection Type",
    "Colors",
  ],
  MacBook: [
    "Model",
    "Chip",
    "RAM",
    "Storage",
    "Size",
    "Battery Life",
    "Operating System",
    "Screen Size",
    "Ports",
    "Chipset",
    "Connection Type",
    "Colors",
  ],
  Projector: [
    "Model",
    "Resolution",
    "Brightness",
    "Projection Technology",
    "Connectivity",
    "Aspect Ratio",
    "Throw Distance",
    "Built-in Speakers",
    "Chipset",
    "Connection Type",
    "Colors",
  ],
  Camera: [
    "Model",
    "Camera Type",
    "Sensor Size",
    "Megapixels",
    "Lens Mount Type",
    "Video Resolution",
    "ISO Range",
    "Battery Life",
    "Connectivity",
    "Screen Type",
    "Chipset",
    "Connection Type",
    "Colors",
  ],
};

export const ColorOptions = [
  "Red",
  "Blue",
  "Green",
  "Black",
  "White",
  "Yellow",
  "Pink",
  "Purple",
  "Gray",
  "Orange",
  "Brown",
  "Cyan",
  "Magenta",
  "Gold",
  "Silver",
  "Beige",
  "Teal",
  "Navy",
  "Maroon",
  "Olive",
  "Lime",
  "Indigo",
  "Violet",
  "Turquoise",
  "Lavender",
  "Coral",
  "Chocolate",
  "Ivory",
  "Amber",
  "Mint",
  "Rose",
  "Salmon",
  "Mustard",
  "Peach",
  "Plum",
  "Azure",
  "Burgundy",
  "Crimson",
  "Emerald",
  "Khaki",
];
